---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python-is-python3
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: task-dev
        image: "venkatnarla3/taskapp:21"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
